### ISSUE TITLE
Rendering with `-rel-link-style directory` only impacts the links in package listings

### ISSUE THREAD

**Issue by achew22** [abhinav/doc2go#154]
First, thanks for the project. This has saved me a HUGE amount of time. I have been trying to integrate this into my teams internal documentation and I think I'm either holding it wrong (most likely) or there is a bug in generation.

When generating, we have added the flag `-rel-link-style directory` which correctly changes the table following the anchor `pkg-directories` to generate links with a trailing `/`, but the links that are generated inline for types, functions, etc., still have their links without the trailing `/`.

Is there another flag that I should be setting here to update those as well?

**Comment by abhinav** [comment]
@achew22 Thanks for the kind words!
No, you're not holding it wrong; that's a bug.

I think we missed a spot when we added this, specifically here:
https://github.com/abhinav/doc2go/blob/e0360133c6d1de9196d5a40aaf03fe500417dc6d/link.go#L36-L38

That gets returned here:
https://github.com/abhinav/doc2go/blob/e0360133c6d1de9196d5a40aaf03fe500417dc6d/generate.go#L218-L220

We set link style only here:
https://github.com/abhinav/doc2go/blob/e0360133c6d1de9196d5a40aaf03fe500417dc6d/main.go#L188

I think to fix this, we just need to add a new field to [docLinker](https://github.com/abhinav/doc2go/blob/e0360133c6d1de9196d5a40aaf03fe500417dc6d/link.go#L13), set it [in main](https://github.com/abhinav/doc2go/blob/e0360133c6d1de9196d5a40aaf03fe500417dc6d/main.go#L149), and use the relLinkStyle.Normalize method in case of the relative package case above.

**Comment by abhinav** [comment]
Fix is out in v0.5.1!
