### ISSUE TITLE
.nojekyll

### ISSUE THREAD

**Issue by 3052** [abhinav/doc2go#174]
by default these items are created:

~~~
_/css/main.css
_/js/permalink.js
index.html
~~~

however the underscore is a problem, as GitHub Jekyll will ignore those items. to fix, you have to add an extra empty file:

~~~
.nojekyll
_/css/main.css
_/js/permalink.js
index.html
~~~

I didn't see this mentioned anywhere.

**Comment by abhinav** [comment]
Thanks for the issue, @3052.

There's some documentation at https://abhinav.github.io/doc2go/docs/embed/jekyll/ on embedding doc2go inside a Jekyll website, and at https://abhinav.github.io/doc2go/docs/publish/github-pages/ for publishing in standalone mode to GitHub.

But yeah, it doesn't cover standalone mode as part of a Jekyll deployment. I'll leave this open as a reminder to go in and add something to the documentation around standalone deployments.
