### ISSUE TITLE
doc pages should have skips to index

### ISSUE THREAD

**Issue by 3052** [abhinav/doc2go#182]
like this:

https://godocs.io/fmt#pkg-index

or this:

https://pkg.go.dev/fmt#pkg-index

**Comment by 3052** [comment]
looks like this is the code in question:

https://github.com/abhinav/doc2go/blob/4534a28d908b94502a438e564ea0e8a76972de8c/internal/html/tmpl/package.html#L7-L15

**Comment by 3052** [comment]
looks like GoDocs includes it in the top nav:

~~~html
<div id="x-projnav">
   <a rel="noopener nofollow" href="/std"><strong>Standard library</strong></a> – fmt
   <span class="float-right">
      <a href="#pkg-index">Index</a> | <a href="#pkg-files">Files</a>
   </span>
</div>
~~~

https://godocs.io/fmt

here:

https://github.com/abhinav/doc2go/blob/4534a28d908b94502a438e564ea0e8a76972de8c/internal/html/tmpl/layout.html#L12-L23

**Comment by 3052** [comment]
https://github.com/abhinav/doc2go/pull/183

**Comment by abhinav** [comment]
Oh, 🤦 , this is adding a link *to* the index, not an anchor for the index.

**Comment by 3052** [comment]
> Oh, 🤦 , this is adding a link _to_ the index, not an anchor for the index.

right 😀. without both its not really useful

**Comment by abhinav** [comment]
Yep, makes sense. Merged! Thanks again!
