### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by 3052** [abhinav/doc2go#184]
pages should have an icon, something like this:

~~~html
<head>
   <link rel="icon" href="hello.png">
</head>
~~~

**Comment by 3052** [comment]
https://godocs.io/favicon.ico
https://pkg.go.dev/static/shared/icon/favicon.ico

**Comment by abhinav** [comment]
This is a good idea! I think I can make a small icon from a cropped portion of the project logo.
(The full logo won't lend itself well to a favicon.)

**Comment by 3052** [comment]
thank you sir
