### ISSUE TITLE
versions link

### ISSUE THREAD

**Issue by 3052** [abhinav/doc2go#187]
with the `-subdir` option, we can navigate down:

1. /hello
2. /hello/v1.3.7
3. /hello/v1.3.7/world

and we can navigate up using the breadcrumbs:

1. /hello/v1.3.7/world
2. /hello/v1.3.7

but currently once you choose a version, you're "stuck" with it, you cannot navigate back up, and have to manually enter the URL, get it from browser history, or use back or similar. other sites have a "versions" link:

- https://godocs.io/go.abhg.dev/doc2go?view=versions
- https://pkg.go.dev/go.abhg.dev/doc2go?tab=versions

we could probably make this happen with something like this:

~~~html
<a href="..">Versions</a>
~~~

**Comment by abhinav** [comment]
Yeah, that's reasonable although I don't want to call it "versions" since 'subdir' is specifically not holding opinions about what the directory is. 

How about a "Go up" link next to the Index link if the subdir option was used?

**Comment by 3052** [comment]
https://github.com/abhinav/doc2go/issues/188

**Comment by 3052** [comment]
go up is a good option - if we do that then can probably close #188 as not needed. I am not set on any one solution, just whatever works

**Comment by abhinav** [comment]
Makes sense. Yeah, I don’t want to do absolute links. I want the html to be relocatable without assuming anything about the deployment.

**Comment by 3052** [comment]
the above solution does not work. my repo docs are at:

~~~
3052.github.io/google
~~~

and this change directs to:

~~~
3052.github.io
~~~

which is a 404

**Comment by abhinav** [comment]
Oh, hm. Yeah, that's wrong. Let me see.

**Comment by 3052** [comment]
I came up with my own fix, but I haven't pushed it yet. I look like the root option if we can make it work, but I dont think it possible in combination with your dictate on relative links. mine is a "go up" approach like you originally suggested

**Comment by abhinav** [comment]
@3052 what configuration did you generate with? Was there a `-home`?

**Comment by abhinav** [comment]
"Go up" is also a valid option; I thought maybe root was preferable but I'm happy with "go up" too.

**Comment by 3052** [comment]
normally I do something like this:

~~~
doc2go -out docs -subdir v1.3.7 -home 154.pages.dev/google ./...
~~~

I dont care root or "go up", whatever is simple but handles the different use cases

**Comment by 3052** [comment]
this is my change, I have not pushed it yet. I have to leave for one hour, here is the code if its helpful:

~~~diff
diff --git a/internal/html/static/css/main.css b/internal/html/static/css/main.css
index f6cb9a6..8c57804 100644
--- a/internal/html/static/css/main.css
+++ b/internal/html/static/css/main.css
@@ -35,8 +35,11 @@ nav {
   border-radius: 0.5em;
   display: flex;
 }
-nav a[href="#pkg-index"] {
-  margin-left: auto;
+nav .left {
+   margin-left: auto;
+}
+nav .right {
+   margin-right: 1em;
 }
 
 /* Remove first level of nesting for a package's index section. */
diff --git a/internal/html/tmpl/layout.html b/internal/html/tmpl/layout.html
index a742340..ea4ed9f 100644
--- a/internal/html/tmpl/layout.html
+++ b/internal/html/tmpl/layout.html
@@ -13,19 +13,23 @@
     {{ template "Head" $ -}}
   </head>
   <body>
-    {{ with .Breadcrumbs -}}
-      <nav>
-        {{ range $idx, $crumb := . -}}
-          {{ if gt $idx 0 }}/{{ end -}}
-          {{ with (relativePath .Path) -}}
-            <a href="{{ . }}">{{ $crumb.Text }}</a>
-          {{- else -}}
-            {{ $crumb.Text -}}
-          {{ end -}}
-        {{ end -}}
-        <a href="#pkg-index">Index</a>
-      </nav>
-    {{- end -}}
+  {{ if .SubDirDepth }}
+    <nav>
+    {{ range $idx, $crumb := .Breadcrumbs -}}
+      {{ if gt $idx 0 }}/{{ end -}}
+      {{ with (relativePath .Path) -}}
+      <a href="{{ . }}">{{ $crumb.Text }}</a>
+      {{- else -}}
+        {{ $crumb.Text -}}
+      {{ end -}}
+    {{ end -}}
+    {{ if .Breadcrumbs }}
+      <a class="left right" href="#pkg-index">Index</a><a href="..">Go up</a>
+    {{ else -}}
+      <a class="left" href="..">Go up</a>
+    {{ end -}}
+    </nav>
+  {{ end }}
     <main>{{ template "Body" $ -}}</main>
     <hr>
     <footer>
~~~

**Comment by abhinav** [comment]
Thanks, @3052.
If I can't fix "Root", I'll switch to Go up with your change.
I suspect it's just a matter of making sure "home" is respected.

**Comment by abhinav** [comment]
@3052 https://github.com/abhinav/doc2go/pull/190 should fix this

**Comment by 3052** [comment]
looks good, thanks. I only tested with `-home` cause thats my use case, but seems to work fine with or without `-subdir`
