### ISSUE TITLE
absolute links

### ISSUE THREAD

**Issue by 3052** [abhinav/doc2go#188]
currently the tool is generating HTML like this for deeper levels:

~~~html
<link href="../../_/css/main.css" rel="stylesheet" />
<link rel="apple-touch-icon" sizes="180x180" href="../../_/icons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="../../_/icons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="../../_/icons/favicon-16x16.png">
<link rel="shortcut icon" href="../../_/icons/favicon.ico">
~~~

I think if we are going to address https://github.com/abhinav/doc2go/issues/187, we might need to consider switching to absolute links. I was thinking a command line flag, maybe `-base`, that defaults to empty string. so by default you would get:

~~~html
<link href="/_/css/main.css" rel="stylesheet" />
~~~

or with `-base /hello` you would get:

~~~html
<link href="/hello/_/css/main.css" rel="stylesheet" />
~~~

**Comment by 3052** [comment]
or instead of  a new flag, you might be able to just parse the `-home` flag. so if you do this:

~~~
-home go.abhg.dev/doc2go
~~~

**Comment by abhinav** [comment]
Per comment in #187, I don't want to do absolute links.
I want to keep the HTML relocatable without regeneration.
I also like that it's browseable locally without an HTTP server.
The solution for #187 will be without changing to absolute links.

**Comment by abhinav** [comment]
Closing as wontfix. #187 can be solved with relative links, and I don't see any other motivation for absolute links.
