### ISSUE TITLE
root/index spacing messed up

### ISSUE THREAD

**Issue by 3052** [abhinav/doc2go#191]
> ![Untitled](https://github.com/abhinav/doc2go/assets/147215885/4ecdd6c5-3dbb-411f-9f2d-d19bb955bf68)

**Comment by abhinav** [comment]
That’s weird. I could’ve sworn it worked right locally. I’ll try to look at it later tonight, unless you already have a fix. Thanks for reporting.

**Comment by 3052** [comment]
disregard. I think it was a caching issue. sorry for the noise
