### ISSUE TITLE
tool should have some way to inject version into HTML

### ISSUE THREAD

**Issue by 3052** [abhinav/doc2go#192]
the current `-subdir` option is great for maintaining multiple versions of a module, or even just as a generic extra folder for some other purpose.

however some people might want to maintain docs for only the current version of a module. in those cases, it would be nice if the version could be injected into the HTML somewhere. currently you MUST use the `-subdir` option for this purpose, even if you only want to maintain one version of the docs. see these two examples:

https://godocs.io/fmt
https://pkg.go.dev/fmt

both include the version, without needing it to be part of the URL

**Comment by abhinav** [comment]
I'm supportive of this, but it's not obvious to me how to surface this cleanly.
Maybe a `-pkg-version` flag that accepts the version number that's then rendered in the HTML.

The version number provided to this flag will be useful as template data when I finally get around to #73.

**Comment by 3052** [comment]
https://github.com/abhinav/doc2go/pull/193
