### ISSUE TITLE
Add an example with godoc-tricks

### ISSUE THREAD

**Issue by oliverpool** [abhinav/doc2go#197]
Hi,

Did you know about https://github.com/fluhus/godoc-tricks ? This is a go module intended to show all the features of the go documentation (for instance the different levels at wich running examples can be attached).

It helped me check the output of my own tool; maybe it might be helpful for you as well.

If you publish it somewhere under https://abhinav.github.io/doc2go/, you can probably ask for a link to be added to its README, just like I did in https://github.com/fluhus/godoc-tricks/pull/18

**Comment by abhinav** [comment]
This is good suggestion. I'll make this change when I have a second, or if someone else wants to take a stab at it, feel free.
