### ISSUE TITLE
Hide Index heading for commands

### ISSUE THREAD

**Issue by astrophena** [abhinav/doc2go#210]
Currently, doc2go puts an Index heading even when generating documentation for commands.

Compare:
- https://go.astrophena.name/tools/cmd/cmdtop (from my [vanity import domain](https://github.com/astrophena/vanity), docs generated by doc2go)
- https://pkg.go.dev/go.astrophena.name/tools/cmd/cmdtop (pkg.go.dev documentation)

I think it can be removed.

**Comment by abhinav** [comment]
👍 Thanks for reporting.
I think the issue is not command-specific, but that the heading is generated even if there's nothing to list.
If there are subpackages, pkg.go.dev will list them there even if it's a command.
Adjusting issue description.

**Comment by abhinav** [comment]
Oops: I misunderstood. Yes, you're right. No need for an Index for main packages.
