### ISSUE TITLE
Standalone website: Client-side search

### ISSUE THREAD

**Issue by abhinav** [abhinav/doc2go#75]
We can use lunr.js or similar to implement client-side search for generated standalone websites.
This will be useful for larger documentation deployments.

**Comment by oliverpool** [comment]
From personal experience, I can recommend https://pagefind.app/

Since it can run after the build step, you might no need to integrate it into doc2go. The user "just" needs to be able to add customize the HTML (to add the search box and link the JS files) and run pagefind on his own.

I couldn't find a way to customize the HTML by looking at the doc, is it possible?

**Comment by abhinav** [comment]
Thanks for the tip, @oliverpool!
I discovered pagefind.app some time after writing this issue, and I was toying with that idea but hadn't committed either way.

Following your comment, I experimented a little and it seems pretty straightforward to integrate. So I agree, this issue should probably use pagefind.

> I couldn't find a way to customize the HTML by looking at the doc, is it possible?

The standalone doc2go website provides very little customization.
This issue is to add explicit support to the standalone template for search.

The way I'm imagining that'll work is a `-pagefind=path/to/exe` flag or something like that--possibly turning on automatically if found on `$PATH`.  If set, we'll add the relevant HTML bits, and run the pagefind binary after generating.

Thinking out loud, with -subdir (#76), we probably want search to be per-subdir. Otherwise, the duplication across the versions may cause confusing jumps (e.g. search in v1.2.3 takes you to the symbol in 1.1.0).

**Comment by oliverpool** [comment]
A way to allow for template customization would be to add 2 flags:
- template dir
- template pattern

If provided, those templates would be parsed (after the builtin templates), allowing the user to override:
- the `head` to link to the JS of pagefind
- the `header` to add the HTML for a search box

This way the user can add the search engine they want!

**Comment by abhinav** [comment]
Thanks, @oliverpool, but I don't currently intend for the standalone website to support template customization. It may support themes in the future, but not the templates. Supporting custom templates greatly increases the breakable surface area, which is not something I want to do right now.

(All's not lost! Note that [Embedded mode](https://abhinav.github.io/doc2go/docs/embed/) already supports that level of customizability—it omits the `<head>` and other page layout sections, and allows you to use a static site generator like Hugo or Jekyll to fill in those bits. I just want to support search without requiring users to switch to embedded mode.)

**Comment by abhinav** [comment]
(FYI, @oliverpool, this was released. Pagefind made it quite a breeze. The results are 👌.)

**Comment by oliverpool** [comment]
Nice work!

The search results inside https://abhinav.github.io/doc2go/std/ are quite good (and fast).
