### ISSUE TITLE
Versioned documentation

### ISSUE THREAD

**Issue by abhinav** [abhinav/doc2go#76]
Figure out a workflow for publishing versioned documentation, i.e. separate documentation websites for v1.2, v1.3, v.1.5, and so on.

**Comment by 3052** [comment]
Yes this is important, both http://pkg.go.dev and http://godocs.io have this

**Comment by 3052** [comment]
this seems to work OK:

~~~
doc2go -out docs/v1.3.7 ./...
~~~

**Comment by 3052** [comment]
this is pretty close:

~~~
doc2go -out docs/v1.3.7 ./...
~~~

but it still needs an index page for the different versions somehow

**Comment by abhinav** [comment]
Yeah, the index page is missing. Right now, that'll basically need to be hand-written or generated by you.

For official multi-version support, I was imagining also tracking which version a symbol was introduced in so that the documentation can include "added in X" next to things.

**Comment by 3052** [comment]
this is a really important feature. this is the one feature that is doing to keep me from using this tool. so if you can add it in ANY way, whether its as part of the path, or part of the title element, or somewhere else in the HTML it would be really helpful. 

I cannot just push documentation without the version being indicated. so until this is resolved I will have to look for another tool or maybe even write my own.

**Comment by 3052** [comment]
OK I think I have a way forward. I am thinking something like this:

~~~
> doc2go -out _site
_site/_/css/main.css
_site/index.html
_site/play/index.html

> doc2go -out _site -tag v1.3.7
_site/_/css/main.css
_site/index.html
_site/v1.3.7/index.html
_site/v1.3.7/play/index.html
~~~

gonna see if I can implement that.

**Comment by 3052** [comment]
https://github.com/abhinav/doc2go/pull/175
